//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.16 at 10:53:10 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.com/spring-boot-webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.webservice.spring_boot_webservice;
